<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <ul>
        <!-- 定义路由 -->
        <li><a href="/home">home</a></li>
        <li><a href="/about">about</a></li>
        <div class="avc">avvv</div>
        <!-- 渲染路由对应的 UI -->
        <div id="routeView"></div>
        <!-- <img src="./jaaao.png"> -->
    </ul>
</body>
<script type="text/javascript">
    // window.addEventListener('DOMContentLoaded', onLoad);
    // window.addEventListener('popstate', onHashChange);
    // routerView = document.querySelector('#routeView');
    // function onLoad(){
    //     onHashChange();
    //     let alist = document.querySelectorAll('a');
    //     alist.forEach((el)=>el.addEventListener('click',function(event){
    //         event.preventDefault();
    //         history.pushState(null,'',el.getAttribute('href'));
    //         onHashChange();
    //     }))
    // }
    // function onHashChange() {
    //     switch (location.hash) {
    //         case '/home':
    //             routerView.innerHTML = 'Home'
    //             return
    //         case '/about':
    //             routerView.innerHTML = 'About'
    //             return
    //         default:
    //             return
    //     }
    // }
//     window.onerror = function(message, source, lineno, colno, error) {
// // message：错误信息（字符串）。
// // source：发生错误的脚本URL（字符串）
// // lineno：发生错误的行号（数字）
// // colno：发生错误的列号（数字）
// // error：Error对象（对象）
// console.log('捕获到异常：',{message, source, lineno, colno, error});
// return true
// }
// setTimeout(() => {
//         Jartto;
//     });

//     window.addEventListener('error', (error) => {
//     console.log('捕获到异常：', error);
    
// }, true)
// window.addEventListener("unhandledrejection", function(e){
//   e.preventDefault()
//   console.log('捕获到异常：', e);
//   return true;
// });
// Promise.reject('promise error').catch((err)=>{
//     console.log(err)
// });
// new Promise((resolve, reject) => {
//   reject('promise error');
// });
// new Promise((resolve) => {
//   resolve();
// }).then(() => {
//   throw 'promise error'
// });
function a() {
  b();
}
function b() {
  c();
}
function c() {
  try {
    throw new Error("an error  occured");
    console.log("will never run");
  } catch (err) {
    console.log(err);
  }
}
a();
</script>

</html>